ORIGINAL_DATA_PATH: data/data.csv
TRAIN_DATA_DIRECTORY: data/train
TEST_DATA_DIRECTORY: data/test
TRAIN_DATA_PATH: data/training_episodes.csv
TRAIN_INDEX_PATH: data/training_index.csv
TEST_DATA_PATH: data/testing_episodes.csv
TEST_INDEX_PATH: data/testing_index.csv
TRAIN_PERCENTAGE: 0.05
TEST_PERCENTAGE: 0.2


EPOCHS: 50
BATCH_SIZE: 256
LEARNING_RATE: 0.0001


GAMMA: 0.95
STATE_DIMENSION: 18
ACTION_DIMENSION: 4
NUM_HEADS: 64
TARGET_UPDATE_INTERVAL: 1000
LOWER_BOUND: 1.41537


CHECKPOINT_PATH: checkpoint/checkpoint.pth
CHECKPOINT_SAVE_INTERVAL: 2000


SUMMARY_PATH: logs
SUMMARY_CHECKPOINT: 1000