ORIGINAL_DATA_PATH: data/data.csv
ORIGINAL_DATA_DIRECTORY: data
TRAIN_DATA_PATH: data/training_episodes.csv
TRAIN_INDEX_PATH: data/training_index.csv
TEST_DATA_PATH: data/testing_episodes.csv
TEST_INDEX_PATH: data/testing_index.csv
TRAIN_PERCENTAGE: 0.7



EPOCHS: 200
BATCH_SIZE: 256
LEARNING_RATE: 0.0005

GAMMA: 0.95
STATE_DIMENSION: 18
ACTION_DIMENSION: 4
NUM_HEADS: 64
TARGET_UPDATE_INTERVAL: 2500


SUMMARY_PATH: logs
SUMMARY_CHECKPOINT: 1000